### ISSUE TITLE
Set up automatic semantic-release

### ISSUE THREAD

**Issue by lidel** [ipfs-shipyard/js-pinning-service-http-client#5]
@SgtPooki I believe what   we need to do is to leverage https://www.npmjs.com/package/semantic-release – already used in https://github.com/ipfs/aegir itself.

Ref. docs: https://github.com/semantic-release/semantic-release#documentation 

- [x] add `NPM_TOKEN` as secret to this repo
- [ ] ensure scripts in `package.json` are set up correctly
  - [ ] make sure `release`  runs `semantic-release` ([example](https://github.com/ipfs/aegir/blob/585b0040f8a5e092e50f49c4a67b34938ad0a87c/package.json#L149))
  - [ ] make sure we use `main` instead of `master`

**Comment by SgtPooki** [comment]
I believe this is already done thanks to aegir.

* https://github.com/ipfs-shipyard/js-pinning-service-http-client/actions/runs/2303698643
* https://github.com/ipfs-shipyard/js-pinning-service-http-client/releases/tag/v1.0.0

![image](https://user-images.githubusercontent.com/1173416/167739365-e1cee371-dd00-457f-9d4e-9685ca2be9f8.png)
